### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by eshaanm25** [DanielSmith1239/HQTriviaMaster#85] opened 2018-03-27 02:22 UTC
![image](https://user-images.githubusercontent.com/37758843/37943103-22331dec-3144-11e8-9f2d-fb6d7796befb.png)

This is the error codes I receive when I try to run, am i doing something wrong?

Thanks in advance

**Comment by DanielSmith1239** [comment] 2018-03-27 02:35
Duplicate of #65.

**Closed by DanielSmith1239** 2018-03-27 02:35 UTC
