### ISSUE TITLE
Cannot get answers after scanning

### ISSUE THREAD

**Issue by Hockeyrocks57** [DanielSmith1239/HQTriviaMaster#41] opened 2018-02-08 16:28 UTC
When I try to get an answer, it won't get any results
![screen shot 2018-02-08 at 11 27 14 am](https://user-images.githubusercontent.com/36273365/35984755-1304a62e-0cc3-11e8-90d7-dfc4d880d240.png)

Thanks in advance

Matt

**Comment by DanielSmith1239** [comment] 2018-02-20 17:37
I’ve noticed this too, I’ll look into it.

**Comment by Eazylikesundaymorning** [comment] 2018-02-21 19:51
Same. I don't know if this has anything to do with it because I don't know if the working version did this...but it seems as if when you click "ok" to confirm API and CSE ID that it does not save.  When I pull up preferences again, my entered keys and ID do not show. I say this because it appears that everything else is working fine codewise.

**Comment by DanielSmith1239** [comment] 2018-02-26 16:10
It does save, but for security reasons, if you reopen the panel the API and CSE that are saved aren't revealed.

**Comment by DanielSmith1239** [comment] 2018-03-12 14:38
Haven't been able to figure out the cause of this. Since it doesn't occur when using the web socket, I'm just going to close this for now because the main feature at this point is the web socket. If someone else looks into this and discovers what's causing the issue, feel free to let me know.

**Closed by DanielSmith1239** 2018-03-12 14:38 UTC
